- type: job
  parent: CMJobBase
  id: RMCSPPRiflemanPVE
  name: rmc-job-name-upp-rifleman
  description: rmc-job-description-upp-rifleman-pve
  playTimeTracker: RMCJobSPPRiflemanPVE
  ranks:
   RMCRankSPPRyadovoy: []
  startingGear: RMCJobSPPRiflemanPVEGear
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  accessGroups:
  - Rifleman
  spawnMenuRoleName: UPP Rifleman (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - UPP
    - type: Skills
      preset: RMCSkillPresetPVERifleman
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-upp-rifleman-pve
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadSPP
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
  hidden: true


- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSPPRiflemanPVE
  name: upp rifleman spawn point
  suffix: PVE
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: spp_spawn
  - type: SpawnPoint
    job_id: RMCSPPRiflemanPVE

- type: startingGear
  id: RMCJobSPPRiflemanPVEGear
  equipment:
    id: RMCIDSPP

- type: playTimeTracker
  id: RMCJobSPPRiflemanPVE
