- type: job
  parent: CMJobBase
  id: RMCSPPSectionLeadPVE
  name: rmc-job-name-upp-sectionsergeant
  description: rmc-job-description-upp-sectionsergeant
  playTimeTracker: RMCJobSPPSectionLeadPVE
  ranks:
    RMCRankSPPStarshiySerzhant: []
  startingGear: RMCJobSPPSectionLeadPVEGear
  icon: "RMCJobIconSPPLeader"
  joinNotifyCrew: false
  accessGroups:
  - SquadLeader
  spawnMenuRoleName: UPP Section Sergeant (PVE)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - UPP
    - type: Skills
      preset: RMCSkillPresetPVESectionSergeant
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-upp-sectionsergeant
    - type: AssignSquad
      whitelist:
        tags:
        - RMCSquadSPP
    - type: MarineOrders
    - type: RMCPointing
    - type: RMCTrackable
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
  hidden: true

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSPPSectionLeadPVE
  name: upp section lead spawn point
  suffix: PVE
  components:
  - type: SpawnPoint
    job_id: RMCSPPSectionLeadPVE
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: spp_spawn

- type: startingGear
  id: RMCJobSPPSectionLeadPVEGear
  equipment:
    id: RMCIDSPP

- type: playTimeTracker
  id: RMCJobSPPSectionLeadPVE
