- type: rank
  id: RMCRankTWEMarine
  name: Marine
  prefix: Mne.
  paygrade: E1

- type: rank
  id: RMCRankTWELanceCorporal
  name: Lance Corporal
  prefix: LCpl.
  paygrade: E2

- type: rank
  id: RMCRankTWECorporal
  name: Corporal
  prefix: Cpl.
  paygrade: E3

- type: rank
  id: RMCRankTWESergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: E4

- type: rank
  id: RMCRankTWEColourSergeant
  name: Colour Sergeant
  prefix: CSgt.
  paygrade: E5

- type: rank
  id: RMCRankTWEWarrantOfficer1
  name: Warrant Officer Class 1
  prefix: WO1.
  paygrade: E6

- type: rank
  id: RMCRankTWEWarrantOfficer2
  name: Warrant Officer Class 2
  prefix: WO2.
  paygrade: E7

- type: rank
  id: RMCRankTWESecondLieutenant
  name: Second Lieutenant
  prefix: 2nd LT
  paygrade: O1

- type: rank
  id: RMCRankTWELieutenant
  name: Lieutenant
  prefix: Lt.
  paygrade: O2

- type: rank
  id: RMCRankTWECaptain
  name: Captain
  prefix: Capt.
  paygrade: O3

- type: rank
  id: RMCRankTWEMajor
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMCRankTWELieutenantColonel
  name: Lieutenant Colonel
  prefix: Lt.Col.
  paygrade: O5

- type: rank
  id: RMCRankTWEColonel
  name: Colonel
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMCRankTWEBrigadier
  name: Brigadier
  prefix: Brig.
  paygrade: O7

- type: rank
  id: RMCRankTWEMajorGeneral
  name: Major General
  prefix: Maj Gen.
  paygrade: O8

- type: rank
  id: RMCRankTWELieutenantGeneral
  name: Lieutenant General
  prefix: Lt Gen.
  paygrade: O9

- type: rank
  id: RMCRankTWEGeneral
  name: General
  prefix: Gen.
  paygrade: O10
  
- type: rank
  id: RMCRankTWEEmpress
  name: Empress # This needs to be changed to allow it to change dynamically for genders
  prefix: HRM.

# The below ranks are for the Para insert on Hybrisa

- type: rank
  id: RMCRankParaPrivate
  name: Private
  prefix: Pte.
  paygrade: E1

- type: rank
  id: RMCRankParaPrivateSecondClass
  name: Private Second Class
  prefix: Pte2.
  paygrade: E2

- type: rank
  id: RMCRankParaLanceCorporal
  name: Lance Corporal
  prefix: LCpl.
  paygrade: E3

- type: rank
  id: RMCRankParaCorporal
  name: Corporal
  prefix: Cpl.
  paygrade: E4

- type: rank
  id: RMCRankParaSergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: RMCRankParaStaffSergeant
  name: Staff Sergeant
  prefix: SSgt.
  paygrade: E6

- type: rank
  id: RMCRankParaWarrantOfficerClass2
  name: Warrant Officer Class 2
  prefix: WO2.
  paygrade: E7

- type: rank
  id: RMCRankParaSecondLieutenant
  name: Second Lieutenant.
  prefix: 2Lt.
  paygrade: O1

- type: rank
  id: RMCRankParaLieutenant
  name: Lieutenant
  prefix: Lt.
  paygrade: O2

- type: rank
  id: RMCRankParaCaptain
  name: Captain
  prefix: Capt.
  paygrade: O3

- type: rank
  id: RMCRankParaMajor
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMCRankParaLieutenantColonel
  name: Lieutenant Colonel
  prefix: LtCol.
  paygrade: O5

- type: rank
  id: RMCRankParaColonel
  name: Colonel
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMCRankParaBrigadier
  name: Brigadier
  prefix: Brig.
  paygrade: O7

- type: rank
  id: RMCRankParaMajorGeneral
  name: Major General
  prefix: MajGen.
  paygrade: O8

- type: rank
  id: RMCRankParaGeneralBrigade
  name: General of the Brigade
  prefix: GenBrig.
  paygrade: O9
