# TWEPA - (Three Suns Empire Policing Authority) - TWE style Police, like the CMB but for heavy TWE focused colonies. Please change when we have a new name for the sector.

- type: rank
  id: RMCRankTWEPAConstable
  name: Constable
  prefix: Cst.

- type: rank
  id: RMCRankTWEPASeniorConstable
  name: Senior Constable
  prefix: Sr. Cst.

- type: rank
  id: RMCRankTWEPASergeant
  name: Sergeant
  prefix: Sgt.

- type: rank
  id: RMCRankTWEPAInspector
  name: Inspector
  prefix: Insp.

- type: rank
  id: RMCRankTWEPAChiefInspector
  name: Chief Inspector
  prefix: Ch. Insp.

- type: rank
  id: RMCRankTWEPACommander
  name: Commander
  prefix: Cmdr.

- type: rank
  id: RMCRankTWEPADeputyCommissioner
  name: Deputy Commissioner
  prefix: Dep. Com.

- type: rank
  id: RMCRankTWEPACommissioner
  name: Commissioner
  prefix: Com.

