- type: job
  parent: CMJobBase
  id: CMUSCMBrigadierGeneral
  name: rmc-job-name-uscm-brigadier-general
  description: rmc-job-description-uscm-brigadier-general
  playTimeTracker: CMJobUSCMBrigadierGeneral
  ranks:
    RMCRankBrigadierGeneral: []
  startingGear: RMCGearUSCMBrigadierGeneral
  icon: "RMCJobIconUSCMBrigadierGeneral"
  joinNotifyCrew: false
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillEndurance: 3
        RMCSkillEngineer: 2
        RMCSkillExecution: 1
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSmartGun: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: MarineOrders
  hidden: true

- type: startingGear
  id: RMCGearUSCMBrigadierGeneral
  equipment:
    jumpsuit: CMJumpsuitGeneral
    outerClothing: RMCCoatJacketGeneralFilled
    shoes: RMCBootsCBRN
    head: RMCHeadCapGeneral
    id: RMCIDCardUSCMBrigadierGeneral
    ears: CMHeadsetHighCommand
    eyes: RMCSunglasses
    gloves: RMCHandsVeteranCBRN
    back: RMCSatchelLightpackFilledHighCommand
    belt: RMCMatebaBeltLuxuriousFilled
    pocket1: RMCPouchMagazinePistolLargeFilledHighCommand
    pocket2: RMCPouchGeneralLarge
  inhand:
    - RMCHeadBeretGeneral

- type: entity
  parent: IDCardStandard # Deliberately parenting off of upstream ID card cause it needs to work with admin access configurator.
  id: RMCIDCardUSCMBrigadierGeneral
  name: brigadier general ID card
  suffix: Admin
  description: Issued to the top brass of the USCM. Premium, sleek, built to last.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/general.rsi
    state: general
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/general.rsi
  - type: Item
    heldPrefix: green
  - type: Access
    groups:
    - ShipMasterAccess
    - Colony
    - Corp
    - RMCWeYa
    tags:
    - CMAccessHighCommand
    - CMAccessXenoQueen
    - CMAccessXeno

- type: playTimeTracker
  id: CMJobUSCMBrigadierGeneral

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconUSCMBrigadierGeneral
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_general
