# TWEPA Constable
- type: job
  parent: CMJobBase
  id: RMCTWEPAConstable
  name: rmc-job-name-tsepa-constable
  description: rmc-job-description-tsepa-Ccnstable
  playTimeTracker: RMCJobTWEPAConstable
  ranks:
    RMCRankTWEPAConstable: []
  startingGear: RMCGearTWEPAConstable
  icon: "RMCJobIconTWEPAConstable"
  joinNotifyCrew: false
  accessGroups:
  - ColonistTWEPA
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMarshal
    - type: NpcFactionMember
      factions:
      - TWE
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-constable
  hidden: true

- type: startingGear
  id: RMCGearTWEPAConstable
  equipment:
    head: RMCHeadCapTWEPA
    ears: RMCHeadsetTWEPA
    jumpsuit: RMCJumpsuitTWEPA
    outerClothing: RMCCoatTWEPAHighVisVest
    gloves: RMCHandsVeteran
    shoes: CMBootsBlackFilled
    id: RMCIDCardTWEPA
    belt: RMCBeltHolsterPistolTWEFilledL54
    back: RMCSatchelTWEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointTWEPAConstable
  name: tsepa constable spawn point
  components:
  - type: SpawnPoint
    job_id: RMCTWEPAConstable
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Objects/Clothing/OuterClothing/CMB/cmb_light_armor.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobTWEPAConstable
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTWEPAConstable
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: tse_paconstable
