# TWEPA Senior Constable
- type: job
  parent: CMJobBase
  id: RMCTWEPASeniorConstable
  name: rmc-job-name-tsepa-senior-constable
  description: rmc-job-description-tsepa-senior-constable
  playTimeTracker: RMCJobTWEPASeniorConstable
  ranks:
    RMCRankTWEPASeniorConstable: []
  startingGear: RMCGearTWEPASeniorConstable
  icon: "RMCJobIconTWEPASeniorConstable"
  joinNotifyCrew: false
  accessGroups:
  - ColonistTWEPABrig
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMarshal
    - type: NpcFactionMember
      factions:
      - TWE
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-senior-constable
    - type: RMCTrackable
  hidden: true

- type: startingGear
  id: RMCGearTWEPASeniorConstable
  equipment:
    head: RMCHeadBeretTWEPA
    ears: RMCHeadsetTWEPA
    jumpsuit: RMCJumpsuitTWEPA
    outerClothing: RMCCoatTWEPA
    gloves: RMCHandsVeteran
    shoes: CMBootsBlackFilled
    id: RMCIDCardTWEPASilverGold
    belt: RMCBeltHolsterRevolverSpearheadFill
    back: RMCSatchelTWEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointTWEPASeniorConstable
  name: tsepa senior constable spawn point
  components:
  - type: SpawnPoint
    job_id: RMCTWEPASeniorConstable
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Objects/Clothing/OuterClothing/CMB/cmb_light_armor.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobTWEPASeniorConstable
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTWEPASeniorConstable
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: tse_paseniorconstable
