# TWEPA Synthetic
- type: job
  parent: CMJobBase
  id: RMCJobTWEPASynthetic
  name: rmc-job-name-tsepa-synth
  description: rmc-job-description-tsepa-synth
  playTimeTracker: RMCJobTWEPASynthetic
  ranks:
    RMCRankTWEPAConstable: [ ]
  startingGear: RMCGearTWEPASynthetic
  icon: "RMCJobIconTWEPASynth"
  joinNotifyCrew: false
  accessGroups:
  - ColonistTWEPAInspector
  - Synth
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 3
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 1
        RMCSkillIntel: 1
        RMCSkillDomestics: 2
    - type: NpcFactionMember
      factions:
      - TWE
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-synth
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: Synth
  hidden: true

- type: startingGear
  id: RMCGearTWEPASynthetic
  equipment:
    head: RMCHeadBeretTWEPA
    ears: RMCHeadsetTWEPA
    jumpsuit: RMCJumpsuitTWEPA
    outerClothing: RMCCoatTWEPAHighVisVest
    gloves: RMCHandsVeteran
    shoes: CMBootsBlackFilled
    id: RMCIDCardTWEPASilverGold
    back: RMCSatchelTWEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointTWEPASynthetic
  name: tsepa synthetic spawn point
  components:
  - type: SpawnPoint
    job_id: RMCJobTWEPASynthetic
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Objects/Clothing/OuterClothing/TWE/TWEPA/highvis_vest.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobTWEPASynthetic
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTWEPASynth
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: tse_pasynth
