# TWEPA Inspector
- type: job
  parent: CMJobBase
  id: RMCTWEPAInspector
  name: rmc-job-name-tsepa-inspector
  description: rmc-job-description-tsepa-inspector
  playTimeTracker: RMCJobTWEPAInspector
  ranks:
    RMCRankTWEPAInspector: []
  startingGear: RMCGearTWEPAInspector
  icon: "RMCJobIconTWEPAInspector"
  joinNotifyCrew: false
  accessGroups:
  - ColonistTWEPAInspector
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEngineer: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillConstruction: 1
        RMCSkillMedical: 2
        RMCSkillEndurance: 3
        RMCSkillCqc: 3
        RMCSkillFirearms: 2
        RMCSkillPolice: 0
        RMCSkillFireman: 2
        RMCSkillLeadership: 2
    - type: MarineOrders
    - type: NpcFactionMember
      factions:
      - TWE
    - type: RMCPointing
    - type: CommandAccent
    - type: JobPrefix
      prefix: rmc-job-prefix-tsepa-inspector
    - type: RMCTrackable
  hidden: true

- type: startingGear
  id: RMCGearTWEPAInspector
  equipment:
    head: RMCHeadCapTWEPAPeaked
    ears: RMCHeadsetTWEPA
    jumpsuit: RMCJumpsuitTWEPA
    gloves: RMCHandsVeteran
    shoes: CMBootsBlackFilled
    id: RMCIDCardTWEPAGold
    belt: RMCBeltHolsterRevolverSpearheadFill
    back: RMCSatchelTWEPA

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointTWEPAInspector
  name: tsepa inspector spawn point
  components:
  - type: SpawnPoint
    job_id: RMCTWEPAInspector
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Objects/Clothing/OuterClothing/CMB/cmb_sheriff_armor.rsi
      state: icon

- type: playTimeTracker
  id: RMCJobTWEPAInspector
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconTWEPAInspector
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: tse_painspector
