- type: roleLoadout
  id: JobRMCCLFStandardPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCCLFDoctorPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCCLFHeavyGunnerPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCCLFCommanderPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins