- type: roleLoadout
  id: JobRMCFORECONPVEAssistantSL
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCFORECONPVECorpsman
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCFORECONPVERifleman
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCFORECONPVESmartgunner
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCFORECONPVESquadLead
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobRMCFORECONPVERadioTelephoneOperator
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins