- type: roleLoadout
  id: JobCMSquadLeaderPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMSmartGunOperatorPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMSectionSergeantPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: CMRiflemanPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPlatoonCommanderPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPlatoonCommanderPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMHospitalCorpsmanPVE
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins