- type: job
  parent: CMSurvivorSecurity
  id: RMCSurvivorHybrisaTWEPAConstable
  name: rmc-job-name-tsepa-constable
  description: cm-job-description-survivor
  ranks:
    RMCRankTWEPASergeant:
    - !type:RoleTimeRequirement
      role: CMJobSurvivorSecurity
      time: 630000 # 175 hours
    RMCRankTWEPASeniorConstable:
    - !type:RoleTimeRequirement
      role: CMJobSurvivorSecurity
      time: 252000 # 70 hours
    RMCRankTWEPAConstable: []
  startingGear: RMCGearSurvivorHybrisaTWEPAConstable
  accessGroups:
  - ColonistAllAccessNoArmory
  - ColonistTWEPA
  spawnMenuRoleName: TWEPA Constable (Hybrisa Survivor)
  icon: "RMCJobIconTWEPAConstable"
  hasIcon: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorMarshal
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetHybrisaConstable
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - TWE
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
  useLoadoutOfJob: CMSurvivorSecurity # for inheritance

- type: startingGear
  parent: RMCGearSurvivorBase
  id: RMCGearSurvivorHybrisaTWEPAConstable
  equipment:
    eyes: RMCGlassesSecurityBlue
    jumpsuit: RMCJumpsuitTWEPA
    belt: RMCBeltHolsterPistolTWEFilledL54
    shoes: RMCShoesLaceup
    id: RMCIDCardTWEPASurvivor
    back: RMCSatchelBlackFillSurvivorConstable
    ears: RMCHeadsetTWEPA

- type: entity
  parent: RMCSurvivorPresetSecurity
  id: RMCSurvivorPresetHybrisaConstable
  name: constable colonist preset
  categories: [ HideSpawnMenu ]
  components:
  - type: SurvivorPreset
    primaryWeapons: [ ]
    randomOutfits:
    - [ RMCHeadCapTWEPAPeaked, RMCCoatTWEPA, RMCPouchMagazineFilledMP5, WeaponSMGMP5 ]
    - [ RMCHeadCapTWEPAPeaked, RMCCoatTWEPAFormal, RMCPouchMagazineFilledMP5, WeaponSMGMP5 ]
    - [ RMCHeadCapTWEPAPeaked, RMCArmorVestTWEPA, RMCPouchShotgunFilledPolicing, RMCWeaponShotgunHG3712, RMCExplosiveBreachingChargeRubberTWEPA ]
    - [ RMCHeadCapTWEPAPeaked, RMCCoatTWEPAHighVis, RMCPouchMagazineFilledMP5, WeaponSMGMP5, RMCHandsCombat ]
    - [ RMCHeadCapTWEPAPeakedGoldSilver, RMCCoatTWEPAHighVisVest, RMCPouchShotgunFilledPolicing, RMCWeaponShotgunHG3712, RMCHandsCombat ]
    - [ RMCHeadCapTWEPAPeakedGold, RMCCoatTWEPAFormal, RMCPouchShotgunFilledPolicing, RMCHandsCombat ]
